version: '3.8'

services:
  rebotlution:
    build:
      context: .
      dockerfile: Dockerfile
    image: rebotlution:latest
    container_name: rebotlution-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs/nginx:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rebotlution-network

networks:
  rebotlution-network:
    driver: bridge

volumes:
  nginx-logs:
    driver: local